db_file: "bot.db"
bot_url: ""
polling_timeout: 10
prompt_start: "Сделай краткий пересказ истории этой переписки, на русском языке. Каждое сообщение начинается с его автора, затем идёт символ ':', после него идут все сообщения от одного пользователя - и они сгруппированы через точку. Если сообщение помечено звёдочками(*) - было выполнено какое-нибудь действие в чате, например отправка фото или видео. Оставляй имена:\n"
messages:
  response:
    start: "Привет! Я буду сохранять историю переписки в чате и давать краткий пересказ по запросу"
    loading_brief: "Готовим краткий пересказ..."
  error:
    default: "Произошла неизвестная ошибка."
