db_file: "bot.db"
bot_url: ""
polling_timeout: 10
prompt_start: "Сделай краткий пересказ истории этой переписки, на русском языке. Оставляй имена:\n"
messages:
  response:
    start: "Привет! Я буду сохранять историю переписки в чате и давать краткий пересказ по запросу"
  error:
    default: "Произошла неизвестная ошибка."
