db_file: "bot.db"

bot_url: ""

messages:
  response:
    start: "Привет! Я буду сохранять историю переписки в чате и давать краткий пересказ по зЯ буду сохранять историю переписки в чате и давать краткий пересказ по запросу"
  error:
    default: "Произошла неизвестная ошибка."
